## 1. Importing Libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.7.0'

## 2. Data Preprocessing

### Importing the dataset

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')

In [4]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [5]:
x = X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [7]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [8]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

### Encoding Catagorical Data

**Label Encoding the gender column**

In [15]:
X[:,2]

array(['Female', 'Female', 'Female', ..., 'Female', 'Male', 'Female'],
      dtype=object)

In [16]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [17]:
X[:,2]

array([0, 0, 0, ..., 0, 1, 0], dtype=object)

**One Hot Encoding for gerography column**

In [18]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [19]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

### Splitting the dataset into the Training set and Test set

In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [22]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## 3. Building the ANN (Artifical Neural Network)

### 1. Initializing the ANN

In [24]:
ann = tf.keras.models.Sequential()

### 2. Adding the input layer and the first hidden layer

In [25]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### 3. Adding the second hidden layer

In [26]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### 4. Adding the output layer

In [27]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Training the ANN

### 1. Compiling the ANN

In [28]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

### 2. Training the ANN on the Training set

In [29]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 14s 6ms/step - loss: 0.6221 - accuracy: 0.7066
Epoch 2/100
250/250 [==============================] - 1s 5ms/step - loss: 0.4779 - accuracy: 0.7989
Epoch 3/100
250/250 [==============================] - 1s 5ms/step - loss: 0.4428 - accuracy: 0.8130: 0s - loss: 0
Epoch 4/100
250/250 [==============================] - 1s 5ms/step - loss: 0.4308 - accuracy: 0.8170
Epoch 5/100
250/250 [==============================] - 2s 6ms/step - loss: 0.4239 - accuracy: 0.8191
Epoch 6/100
250/250 [==============================] - 1s 6ms/step - loss: 0.4192 - accuracy: 0.8204
Epoch 7/100
250/250 [==============================] - 1s 6ms/step - loss: 0.4142 - accuracy: 0.8241
Epoch 8/100
250/250 [==============================] - 1s 5ms/step - loss: 0.4082 - accuracy: 0.8267
Epoch 9/100
250/250 [==============================] - 1s 6ms/step - loss: 0.4018 - accuracy: 0.8296
Epoch 10/100
250/250 [==============================] - 1s 5ms/step - loss: 

250/250 [==============================] - 2s 6ms/step - loss: 0.3364 - accuracy: 0.8614
Epoch 81/100
250/250 [==============================] - 1s 6ms/step - loss: 0.3360 - accuracy: 0.8634
Epoch 82/100
250/250 [==============================] - 1s 6ms/step - loss: 0.3364 - accuracy: 0.8616
Epoch 83/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3361 - accuracy: 0.8624
Epoch 84/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3360 - accuracy: 0.8631
Epoch 85/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3362 - accuracy: 0.8610
Epoch 86/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3358 - accuracy: 0.8626
Epoch 87/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3361 - accuracy: 0.8621
Epoch 88/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3357 - accuracy: 0.8622
Epoch 89/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3358 - accuracy: 

## Making the predictions and evaluating the model

### Predicting the result of a single observation

In [30]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


### Predicting the Test set results

In [31]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [32]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1509   86]
 [ 190  215]]


0.862